### PR TITLE
Embedding repositories affected by a security vulnerability by @babel/traverse in Asp.NET with React

### PR DESCRIPTION
**Pull request by MadeshGiri**
https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/334152  Fixed the vulnerability issue caused by @babel/traverse

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi @MadeshGiri ,
Where is package.json changes? Don't commit package-lock.json. Please delete the file. Additionally attach the running sample screenshot in PR.

Regards,
selvamani R.

**Comment by MadeshGiri** [comment]
Hi @Selvamani-Ramakrishnan ,
I have made changes in package.json file The sample is running properly able to render dashboard.
image

**Review by ghost — APPROVED** [review]
No concerns

**Review by vinothkumar1732 — APPROVED** [review]
Code change is fine.

**Pull request merged**
